[features]
seeds = false
skip-lint = false

[programs.devnet]
opinion_market = "2BeTz2C9kxK4acaxrAjPwH9Y9KBFGGRzkE3zXr3MwG6h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 